version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - chmod +x scripts/*.sh
      - echo Build started on `date`
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/*
